#!/usr/bin/env ruby
# Runs the sliding puzzle sim.

$: << '.'

require 'board'
require 'logic'

@solved_board = Board.generate(3)
@unsolved_board = @solved_board.shuffle
@number_of_moves = 0

def print_current_state
    puts @unsolved_board
end

def print_move(tile_to_slide)
    current_tile_value = @unsolved_board.get(tile_to_slide[0], tile_to_slide[1])
    puts "#{@number_of_moves}: #{current_tile_value} (#{tile_to_slide[0]}, #{tile_to_slide[1]}) -> (#{@unsolved_board.gap_column}, #{@unsolved_board.gap_row})"
end

while (@unsolved_board != @solved_board)
    print_current_state
    
    tile_to_slide = choose_tile_to_slide(@unsolved_board.dup, @solved_board.dup)

    print_move(tile_to_slide)

    @unsolved_board.slide!(*tile_to_slide)
    @number_of_moves += 1
end
