#!/usr/bin/env ruby
# Runs the sliding puzzle sim.

$: << '.'

require 'board'
require 'logic'

@solved_board = Board.generate(2)
@unsolved_board = @solved_board.shuffle
@number_of_moves = 0

def print_current_state
    puts @unsolved_board
end

def print_move(tile)
    puts "#{@number_of_moves}: #{tile} #{@unsolved_board.position_of(tile)} -> #{@unsolved_board.gap}"
end

print_current_state

start(@unsolved_board.dup, @solved_board.dup)

while (@unsolved_board != @solved_board)
    tile_to_slide = choose_tile_to_slide(@unsolved_board, @solved_board)

    print_move(tile_to_slide)

    @unsolved_board = @unsolved_board.slide(tile_to_slide)
    @number_of_moves += 1

    print_current_state
end

puts
puts "Total number of moves:  #{@number_of_moves}"
puts "Total number of slides: #{Board.slide_calls}"
